/****************************************************************************
 *                                                                          *
 *         Copyright (c) 2010 by Sunplus-prof Technology Co., Ltd.          *
 *                                                                          *
 *  This software is copyrighted by and is the property of Sunplus-prof     *
 *  Technology Co., Ltd. All rights are reserved by Sunplus-prof Technology *
 *  Co., Ltd. This software may only be used in accordance with the         *
 *  corresponding license agreement. Any unauthorized use, duplication,     *
 *  distribution, or disclosure of this software is expressly forbidden.    *
 *                                                                          *
 *  This Copyright notice MUST not be removed or modified without prior     *
 *  written consent of Sunplus-prof Technology Co., Ltd.                    *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd. reserves the right to modify this     *
 *  software without notice.                                                *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd.                                       *
 *  2nd Floor,R2-B,Hi-tech.S,7th Road, Shenzhen High-tech Industrial Park   *
 *  Shenzhen, China                                                         *
 *                                                                          *
 *  Author: Joe Zhao                                                        *
 *                                                                          *
 ****************************************************************************/
/* Sunplus-prof   Joe Zhao   March,18,2024  17:57:24 For SPCA1628A */
#include "app_menu_api.h"

menuexe code MenuExe[] = 
{
	menuModeStill,	menuImageSizeInit,	menuImagesizeSet,	menuImagesizeSet,
	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,
	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	menuFDMeteringSet,	menuFDMeteringSet,	NULL,
	menuSharpnessSet,	menuSharpnessSet,	menuSharpnessSet,	NULL,
	menuSaturationSet,	menuSaturationSet,	menuSaturationSet,	NULL,
	menuContrastSet,	menuContrastSet,	menuContrastSet,	NULL,
	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,
	menuWBModeSet,	menuAEModeInit,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	menuSpeedyCapSet,	menuSpeedyCapSet,
	NULL,	menuSpeedyCapRecSet,	menuSpeedyCapRecSet,	NULL,
	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,
	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,	NULL,
	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,
	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,
	NULL,	mneuPhotoFrameSet,	mneuPhotoFrameSet,	mneuPhotoFrameSet,
	mneuPhotoFrameSet,	mneuPhotoFrameSet,	NULL,	NULL,
	NULL,	NULL,	menuLastItemProcess,	menuIsoSet,
	menuIsoSet,	menuIsoSet,	menuIsoSet,	menuIsoSet,
	menuModeVideo,	menuMovieSizeInit,	menuMovieSizeSet,	menuMovieSizeSet,
	menuMovieSizeSet,	menuMovieSizeSet,	menuMovieSizeSet,	NULL,
	menuFrameRateSet,	menuFrameRateSet,	menuFrameRateSet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,
	menuWBModeSet,	NULL,	menuSnapEffectSet,	menuSnapEffectSet,
	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,
	menuSnapEffectSet,	NULL,	NULL,	NULL,
	NULL,	menuLastItemProcess,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	menuModePlayback,	menuFirstItemProcess,
	menuLockFile,	menuLockOne,	menuLockOne,	menuLockFile,
	menuLockAll,	menuLockAll,	menuLockFile,	menuUnlockAll,
	menuUnlockAll,	menuDeleteInit,	menuDeleteFile,	menuDeleteOne,
	menuDeleteOne,	menuDeleteFile,	menuDeleteAll,	menuDeleteAll,
	menuSlideShowInit,	menuSlideShowSet,	menuSlideShowSet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	menuSlideShowSet,	NULL,	NULL,
	NULL,	menuImageEffectSet,	menuImageEffectSet,	menuImageEffectSet,
	menuImageEffectSet,	menuImageEffectSet,	menuImageEffectSet,	menuImageEffectSet,
	menuImageEffectSet,	menuImageEffectSet,	menuImageEffectSet,	menuImageEffectSet,
	NULL,	menuDistortionSet,	menuDistortionSet,	menuDistortionSet,
	menuDistortionSet,	menuDistortionSet,	menuDistortionSet,	menuDistortionSet,
	menuDistortionSet,	menuDistortionSet,	menuDistortionSet,	menuDistortionSet,
	menuDistortionSet,	NULL,	menuRotateSet,	menuRotateSet,
	menuRotateSet,	NULL,	menuResizeSet,	menuResizeSet,
	menuResizeSet,	menuResizeSet,	menuResizeSet,	menuResizeSet,
	NULL,	menuVoiceMemoSet,	menuVoiceMemoSet,	menuLastItemProcess,
	menuStartImageSet,	NULL,	menuModeStill,	menuImageSizeInit,
	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,
	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,
	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,	menuImagesizeSet,
	NULL,	menuDateStampSet,	menuDateStampSet,	NULL,
	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,
	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,	menuSceneModeSet,
	NULL,	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,
	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,	menuSnapEffectSet,
	menuAEModeInit,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	NULL,	menuWBModeSet,
	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,
	NULL,	menuIsoSet,	menuIsoSet,	menuIsoSet,
	menuIsoSet,	menuIsoSet,	NULL,	menuAntishakeSet,
	menuAntishakeSet,	NULL,	menuFDModeSet,	menuFDModeSet,
	menuLastItemProcess,	menuSmileModeSet,	menuSmileModeSet,	menuModeVideo,
	menuMovieSizeInit,	menuMovieSizeSet,	menuMovieSizeSet,	menuMovieSizeSet,
	NULL,	menuDateStampSet,	menuDateStampSet,	menuAEModeInit,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,	menuAEModeSet,
	menuAEModeSet,	menuLastItemProcess,	menuWBModeSet,	menuWBModeSet,
	menuWBModeSet,	menuWBModeSet,	menuWBModeSet,	menuModeSetup,
	menuRTCInit,	menuRTCSet,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	menuRTCSet,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	menuRTCSet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	menuRTCSet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	menuRTCSet,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	menuRTCSet,	NULL,	NULL,	NULL,
	menuLanguageInit,	menuLanguageSet,	menuLanguageSet,	menuLanguageSet,
	menuLanguageSet,	menuLanguageSet,	menuLanguageSet,	menuLanguageSet,
	menuLanguageSet,	menuLanguageSet,	menuLanguageSet,	menuLanguageSet,
	menuLanguageSet,	NULL,	menuSpeakSoundSet,	menuSpeakSoundSet,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	menuFormatSet,	menuFormatSet,	NULL,
	menuResetSet,	NULL,	menuLastItemProcess,	menuVersionProcess,
	NULL,	NULL,	NULL,	NULL,
	NULL,	menuFormatSet,	menuFormatSet,	NULL,
	menuDeleteOne,	menuDeleteOne,	NULL,	menuBlinkSave,
	menuBlinkSave,	NULL,	menuJpgCrop,	menuJpgCrop,
	NULL,	menuRedEyeSave,	menuRedEyeSave,	menuRedEyeSave,
	menuModeDPS,	menuFirstItemProcess,	menuDpsImageChoose,	menuDpsImageChoose,
	menuDpsImageChoose,	menuDpsCopyInit,	menuDpsCpoySet,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	NULL,	NULL,	NULL,	NULL,
	menuLastItemProcess,	menuDPSResetSet,	NULL,	menuModeCalibration,
	menuCalUsbPowerSet,	NULL,	NULL,	menuCalCDSP_OBSet,
	menuCalCDSP_OBSet,	NULL,	menuCalCDSP_LensShadingSet,	menuCalCDSP_LensShadingSet,
	NULL,	menuCalCDSP_GammaSet,	menuCalCDSP_GammaSet,	NULL,
	menuCalCDSP_AESet,	menuCalCDSP_AESet,	menuCalCDSP_AESet,	menuCalCDSP_AESet,
	NULL,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,
	menuCalCDSP_AEGidSet,	menuCalCDSP_AEGidSet,	NULL,	menuCalCDSP_AWBSet,
	menuCalCDSP_AWBSet,	NULL,	menuCalSnapTest,	menuCalSnapTest,
	menuCalSnapTest,	NULL,	menuCalPvTest,	menuCalPvTest,
	menuCalPvTest,	NULL,	menuCalAETest,	menuCalAETest,
	menuCalAETest,	menuCalAETest,	menuCalOB,	menuCalAutoOB,
	menuCalPvOB,	menuCalAWBTest,	NULL,	menuCalBpPro,
	menuCalBpPro,	menuCalBpPro,	menuCalBpPro,	NULL,
	menuCalAFTurn,	menuCalAFTurn,	menuCalAFTurn,	menuCalFwUpgrade,
	menuCalLsc,	menuCalAECal,	NULL,	menuCalWdtSet,
	menuCalWdtSet,	NULL,	menuCalShowColorPalette,	menuStorageSpeedTest,
	NULL,	menuCalAwbCtt,	menuCalAwbCtt,	NULL,
	menuModeUsbSet,	menuModeUsbSet,
};

menuexe code* code CustomMenuExe[] = 
{
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
	MenuExe,
};

