/****************************************************************************
 *                                                                          *
 *         Copyright (c) 2010 by Sunplus-prof Technology Co., Ltd.          *
 *                                                                          *
 *  This software is copyrighted by and is the property of Sunplus-prof     *
 *  Technology Co., Ltd. All rights are reserved by Sunplus-prof Technology *
 *  Co., Ltd. This software may only be used in accordance with the         *
 *  corresponding license agreement. Any unauthorized use, duplication,     *
 *  distribution, or disclosure of this software is expressly forbidden.    *
 *                                                                          *
 *  This Copyright notice MUST not be removed or modified without prior     *
 *  written consent of Sunplus-prof Technology Co., Ltd.                    *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd. reserves the right to modify this     *
 *  software without notice.                                                *
 *                                                                          *
 *  Sunplus-prof Technology Co., Ltd.                                       *
 *  2nd Floor,R2-B,Hi-tech.S,7th Road, Shenzhen High-tech Industrial Park   *
 *  Shenzhen, China                                                         *
 *                                                                          *
 *  Author: Joe Zhao                                                        *
 *                                                                          *
 ****************************************************************************/
/* Sunplus-prof   Joe Zhao   February,26,2024  14:43:45 For SPCA1628A */
/* This file is created by tool, don't modify it!!! */

#ifndef _MENU_RES_H_
#define _MENU_RES_H_

[LANGUAGE]english:

[MARK]MENU_MARK_STILL_NOUSE:
"Still Record",		"mode_still.bmp",		[()menuModeStill],
	"Resolution",		[menuImageSizeActive(ImageSize)menuImageSizeInit],
		"3456x2592",		"resolution_9m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"3264x2448",		"resolution_8m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"3648x2048(16:9)",		"resolution_7m_16_9.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"2592x1944",		"resolution_5m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"2048x1536",		"resolution_3m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"1600x1200",		"resolution_2m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"1920x1080(16:9)",		"resolution_2m_16_9.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"1280x720(16:9)",		"resolution_1m_16_9.bmp",		[(ImageSize)menuImagesizeSet],
		"1024x768",		"resolution_1m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"640x480",		"resolution_vga.bmp",		[(ImageSize)menuImagesizeSet],
	"Quality",		[(ImageQuality)],
		"Super Fine",		"quality_super_fine.bmp",		[(ImageQuality)],
		"Fine",		"quality_fine.bmp",		[(ImageQuality)],
		"Normal",		"quality.bmp",		[(ImageQuality)],
	"Metering",		[(AEMetering)],
		"Center",		"metering_center.bmp",		[(AEMetering)],
		"Multi",		"metering_multi.bmp",		[(AEMetering)],
		"Spot",		"metering_spot.bmp",		[(AEMetering)],
	"FD Metering",		[menuFDIsActive(FDMetering)],
		"On",		"on.bmp",		[(FDMetering)menuFDMeteringSet],
		"Off",		"off.bmp",		[(FDMetering)menuFDMeteringSet],
	"Sharpness",		[(Sharpness)],
		"High",		"sharpness_soft.bmp",		[(Sharpness)menuSharpnessSet],
		"Normal",		"sharpness_hard.bmp",		[(Sharpness)menuSharpnessSet],
		"Low",		"sharpness.bmp",		[(Sharpness)menuSharpnessSet],
	"Saturation",		[(Saturation)],
		"High",		"saturation_high.bmp",		[(Saturation)menuSaturationSet],
		"Normal",		"saturation_normal.bmp",		[(Saturation)menuSaturationSet],
		"Low",		"saturation_low.bmp",		[(Saturation)menuSaturationSet],
	"Contrast",		[(Contrast)],
		"High",		"contrast_high.bmp",		[(Contrast)menuContrastSet],
		"Normal",		"contrast_normal.bmp",		[(Contrast)menuContrastSet],
		"Low",		"contrast_low.bmp",		[(Contrast)menuContrastSet],
	"White Balance",		[(WBMode)],
		"Auto",		"wb_auto.bmp",		[(WBMode)menuWBModeSet],
		"Daylight",		"wb_day.bmp",		[(WBMode)menuWBModeSet],
		"Cloudy",		"wb_cloudy.bmp",		[(WBMode)menuWBModeSet],
		"Fluorescent",		"wb_flourscent_h.bmp",		[(WBMode)menuWBModeSet],
		"Tungsten",		"wb_tungsten.bmp",		[(WBMode)menuWBModeSet],
	"Exposure",		[(AEMode)menuAEModeInit],
		"-2.0",		"ev_n20.bmp",		[(AEMode)menuAEModeSet],
		"-1.7",		"ev_n17.bmp",		[(AEMode)menuAEModeSet],
		"-1.3",		"ev_n13.bmp",		[(AEMode)menuAEModeSet],
		"-1.0",		"ev_n10.bmp",		[(AEMode)menuAEModeSet],
		"-0.7",		"ev_n07.bmp",		[(AEMode)menuAEModeSet],
		"-0.3",		"ev_n03.bmp",		[(AEMode)menuAEModeSet],
		"+0.0",		"ev_00.bmp",		[(AEMode)menuAEModeSet],
		"+0.3",		"ev_p03.bmp",		[(AEMode)menuAEModeSet],
		"+0.7",		"ev_p07.bmp",		[(AEMode)menuAEModeSet],
		"+1.0",		"ev_p10.bmp",		[(AEMode)menuAEModeSet],
		"+1.3",		"ev_p13.bmp",		[(AEMode)menuAEModeSet],
		"+1.7",		"ev_p17.bmp",		[(AEMode)menuAEModeSet],
		"+2.0",		"ev_p20.bmp",		[(AEMode)menuAEModeSet],
	"Driver Mode",		[menuDriverModeActive(DriverMode)],
		"Off",		"off.bmp",		[(DriverMode)],
		"Self-timer 2S",		"selftimer_2sec.bmp",		[(DriverMode)],
		"Self-timer 5S",		"selftimer_5sec.bmp",		[(DriverMode)],
		"Self-timer 10S",		"selftimer_10sec.bmp",		[(DriverMode)],
		"Burst",		"burst.bmp",		[menuBurstIsActive(DriverMode)],
	"Speedy Capture",		[menuSpeedyCapActive(SpeedyCap)],
		"On",		"on.bmp",		[(SpeedyCap)menuSpeedyCapSet],
		"Off",		"off.bmp",		[(SpeedyCap)menuSpeedyCapSet],
	"Speedy Capture Rec",		[menuSpeedyCapRecActive(SpeedyCapRec)],
		"On",		"on.bmp",		[(SpeedyCapRec)menuSpeedyCapRecSet],
		"Off",		"off.bmp",		[(SpeedyCapRec)menuSpeedyCapRecSet],
	"Effect",		[(ImageEffect)],
		"Normal",		"dsp_normal.bmp",		[(ImageEffect)menuSnapEffectSet],
		"B&W",		"dsp_bw.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Sepia",		"dsp_sepia.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Negative",		"dsp_negative.bmp",		[menuPvEffectActive(ImageEffect)menuSnapEffectSet],
		"Red",		"dsp_r.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Green",		"dsp_g.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Blue",		"dsp_b.bmp",		[(ImageEffect)menuSnapEffectSet],
	"Scene Mode",		[(SceneMode)],
		"Auto",		"scene_auto.bmp",		[(SceneMode)menuSceneModeSet],
		"Landscape",		"scene_landscape.bmp",		[(SceneMode)menuSceneModeSet],
		"Night Scenery",		"scene_nightscenery.bmp",		[(SceneMode)menuSceneModeSet],
		"Portrait",		"scene_portrait.bmp",		[(SceneMode)menuSceneModeSet],
		"Night Portrait",		"scene_nightportrait.bmp",		[(SceneMode)menuSceneModeSet],
		"Beach",		"scene_beach.bmp",		[(SceneMode)menuSceneModeSet],
		"Sport",		"scene_sport.bmp",		[(SceneMode)menuSceneModeSet],
		"Dinner",		"scene_dinner.bmp",		[(SceneMode)menuSceneModeSet],
	"Photo Frame",		[menuPhotoframeIsActive(PhotoFrame)],
		"Off",		[(PhotoFrame)mneuPhotoFrameSet],
		"Frame A",		[(PhotoFrame)mneuPhotoFrameSet],
		"Frame B",		[(PhotoFrame)mneuPhotoFrameSet],
		"Frame C",		[(PhotoFrame)mneuPhotoFrameSet],
		"Frame D",		[(PhotoFrame)mneuPhotoFrameSet],
	"Date Stamp",		[(StampMode)],
		"Off",		"off.bmp",		[(StampMode)],
		"Date",		"print_date.bmp",		[(StampMode)],
		"Date&Time",		"print_dateandtime.bmp",		[(StampMode)],
	"ISO",		[(Iso)menuLastItemProcess],
		"Auto",		"ISO_Auto.bmp",		[(Iso)menuIsoSet],
		"100",		"ISO_100.bmp",		[(Iso)menuIsoSet],
		"200",		"ISO_200.bmp",		[(Iso)menuIsoSet],
		"400",		"ISO_400.bmp",		[(Iso)menuIsoSet],
		"800",		"ISO_800.bmp",		[(Iso)menuIsoSet],
[MARK]MENU_MARK_VIDEO_NOUSE:
"VideoMenu",		"mode_video.bmp",		[()menuModeVideo],
	"Movie Size",		[(VideoSize)menuMovieSizeInit],
		"1920x1080",		"movie_size_fhd.bmp",		[menuVideoSizeIsActive(VideoSize)menuMovieSizeSet],
		"1280x720",		"movie_size_hd.bmp",		[menuVideoSizeIsActive(VideoSize)menuMovieSizeSet],
		"848x480",		"movie_size_d1.bmp",		[menuVideoSizeIsActive(VideoSize)menuMovieSizeSet],
		"640x480",		"movie_size_640.bmp",		[(VideoSize)menuMovieSizeSet],
		"320x240",		"movie_size_320.bmp",		[(VideoSize)menuMovieSizeSet],
	"Frame Rate",		[(FrameRate)],
		"High",		"frame_rate_60.bmp",		[menuFrameIsActive(FrameRate)menuFrameRateSet],
		"Middle",		"frame_rate_30.bmp",		[menuFrameIsActive(FrameRate)menuFrameRateSet],
		"Low",		"frame_rate_15.bmp",		[menuFrameIsActive(FrameRate)menuFrameRateSet],
	"Metering",		[(AEMetering)],
		"Center",		"metering_center.bmp",		[(AEMetering)],
		"Multi",		"metering_multi.bmp",		[(AEMetering)],
		"Spot",		"metering_spot.bmp",		[(AEMetering)],
	"White Balance",		[(WBMode)],
		"Auto",		"wb_auto.bmp",		[(WBMode)menuWBModeSet],
		"Daylight",		"wb_day.bmp",		[(WBMode)menuWBModeSet],
		"Cloudy",		"wb_cloudy.bmp",		[(WBMode)menuWBModeSet],
		"Fluorescent",		"wb_flourscent_h.bmp",		[(WBMode)menuWBModeSet],
		"Tungsten",		"wb_tungsten.bmp",		[(WBMode)menuWBModeSet],
	"Effect",		[(ImageEffect)],
		"Normal",		"dsp_normal.bmp",		[(ImageEffect)menuSnapEffectSet],
		"B&W",		"dsp_bw.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Sepia",		"dsp_sepia.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Negative",		"dsp_negative.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Red",		"dsp_r.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Green",		"dsp_g.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Blue",		"dsp_b.bmp",		[(ImageEffect)menuSnapEffectSet],
	"Date Stamp",		[(StampVideoMode)],
		"Off",		"off.bmp",		[(StampVideoMode)],
		"Date",		"print_date.bmp",		[(StampVideoMode)],
		"Date&Time",		"print_dateandtime.bmp",		[(StampVideoMode)],
	"Advance Denoise",		[(AdvanceDenoise)menuLastItemProcess],
		"On",		"on.bmp",		[(AdvanceDenoise)],
		"Off",		"off.bmp",		[(AdvanceDenoise)],
[MARK]MENU_MARK_AUDIO:
"AudioMenu",		"mode_voice.bmp",
	"Audio Qulity",
		"48KHz",
		"22KHz",
		"8KHz",
	"Resolution(No card)",		[(ImageSizeNoCard)],
		"3456x2592",		[(ImageSizeNoCard)],
		"3648x2048(16:9)",		[(ImageSizeNoCard)],
		"2592x1944",		[(ImageSizeNoCard)],
		"2048x1536",		[(ImageSizeNoCard)],
		"1600x1200",		[(ImageSizeNoCard)],
		"1920x1080(16:9)",		[(ImageSizeNoCard)],
		"1024x768",		[(ImageSizeNoCard)],
		"640x480",		[(ImageSizeNoCard)],
	"Movie Size(No card)",		[(VideoSizeNoCard)],
		"1920x1080",		[(VideoSizeNoCard)],
		"1280x720",		[(VideoSizeNoCard)],
		"848x480",		[(VideoSizeNoCard)],
		"640x480",		[(VideoSizeNoCard)],
		"320x240",		[(VideoSizeNoCard)],
	"AudInAviRec",		[(AudInAviRec)],
		"On",		[(AudInAviRec)],
		"Off",		[(AudInAviRec)],
	"AudInAviPlay",		[(AudInAviPlay)],
		"On",		[(AudInAviPlay)],
		"Off",		[(AudInAviPlay)],
[MARK]MENU_MARK_PLAYBACK:
"Playback",		"mode_playback.bmp",		[()menuModePlayback],
	"Lock...",		[menuProtectIsActive()menuFirstItemProcess],
		"Lock/Unlock one",		[()menuLockFile],
			"Yes",		[()menuLockOne],
			"No",		[()menuLockOne],
		"Lock All",		[()menuLockFile],
			"Yes",		[()menuLockAll],
			"No",		[()menuLockAll],
		"Unlock All",		[()menuLockFile],
			"Yes",		[()menuUnlockAll],
			"No",		[()menuUnlockAll],
	"Delete...",		[menuDeleteIsActive()menuDeleteInit],
		"One",		[()menuDeleteFile],
			"Yes",		[()menuDeleteOne],
			"No",		[()menuDeleteOne],
		"All",		[()menuDeleteFile],
			"Yes",		[()menuDeleteAll],
			"No",		[()menuDeleteAll],
	"Slide Show...",		[menuSlideShowIsActive()menuSlideShowInit],
		"Start",		[menuSlideStartIsActive()menuSlideShowSet],
		"Interval",		[(Interval)menuSlideShowSet],
			"1sec",		[(Interval)],
			"2sec",		[(Interval)],
			"3sec",		[(Interval)],
			"4sec",		[(Interval)],
			"5sec",		[(Interval)],
			"6sec",		[(Interval)],
			"7sec",		[(Interval)],
			"8sec",		[(Interval)],
			"9sec",		[(Interval)],
			"10sec",		[(Interval)],
		"Repeat",		[(Repeat)menuSlideShowSet],
			"Yes",		[(Repeat)],
			"No",		[(Repeat)],
	"Effect",		[menuEffectIsActive()],
		"B&W",		[()menuImageEffectSet],
		"Sepia",		[()menuImageEffectSet],
		"Negative",		[()menuImageEffectSet],
		"Red",		[()menuImageEffectSet],
		"Green",		[()menuImageEffectSet],
		"Blue",		[()menuImageEffectSet],
		"Binarize",		[()menuImageEffectSet],
		"Sunset",		[()menuImageEffectSet],
		"Warm",		[()menuImageEffectSet],
		"Cold",		[()menuImageEffectSet],
		"Contrast",		[()menuImageEffectSet],
	"Distortion",		[menuEffectIsActive()],
		"H-Pinch",		[()menuDistortionSet],
		"H-Punch",		[()menuDistortionSet],
		"V-Pinch",		[()menuDistortionSet],
		"V-Punch",		[()menuDistortionSet],
		"H-Stretch",		[()menuDistortionSet],
		"H-Shrink",		[()menuDistortionSet],
		"V-Stretch",		[()menuDistortionSet],
		"V-Shrink",		[()menuDistortionSet],
		"Wavy",		[()menuDistortionSet],
		"Hourglass",		[()menuDistortionSet],
		"Bubble",		[()menuDistortionSet],
		"BubbleFill",		[()menuDistortionSet],
	"Rotate...",		[menuRotateIsActive()],
		"Rotate",		[()menuRotateSet],
		"Save",		[()menuRotateSet],
		"Back",		[()menuRotateSet],
	"Resize...",		[menuResizeIsActive()],
		"2592x1944",		[menuResizeSizeIsActive()menuResizeSet],
		"2048x1536",		[menuResizeSizeIsActive()menuResizeSet],
		"1600x1200",		[menuResizeSizeIsActive()menuResizeSet],
		"1920x1080(16:9)",		[menuResizeSizeIsActive()menuResizeSet],
		"1024x768",		[menuResizeSizeIsActive()menuResizeSet],
		"640x480",		[menuResizeSizeIsActive()menuResizeSet],
	"Voice Memo...",		[menuVoiceMemoIsActive()],
		"Add",		[menuVoiceMemoAddIsActive()menuVoiceMemoSet],
		"Delete",		[menuVoiceMemoDeleteIsActive()menuVoiceMemoSet],
	"Start-up Image...",		[menuStartupIsActive()menuLastItemProcess],
		"Set",		[()menuStartImageSet],
		"Cancel",
[MARK]MENU_MARK_STILL:
"Still Record",		"mode_still.bmp",		[()menuModeStill],
	"Resolution",		[menuImageSizeActive(ImageSize)menuImageSizeInit],
		"8160x6120",		"resolution_50m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"7664x5748",		"resolution_44m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"7488x5616",		"resolution_42m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"6944x5208",		"resolution_36m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"5600x4200",		"resolution_24m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"5120x3840",		"resolution_20m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"4608x3456",		"resolution_16m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"3888x2916",		"resolution_12m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"3664x2748",		"resolution_10m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"3264x2448",		"resolution_8m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"2592x1944",		"resolution_5m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
		"2048x1536",		"resolution_3m.bmp",		[menuSizeIsActive(ImageSize)menuImagesizeSet],
	"Date Stamp",		[(StampMode)],
		"Off",		"off.bmp",		[(StampMode)menuDateStampSet],
		"On",		"on.bmp",		[(StampMode)menuDateStampSet],
	"Scene Mode",		[(SceneMode)],
		"Auto",		"scene_auto.bmp",		[(SceneMode)menuSceneModeSet],
		"Landscape",		"scene_landscape.bmp",		[(SceneMode)menuSceneModeSet],
		"Night Scenery",		"scene_nightscenery.bmp",		[(SceneMode)menuSceneModeSet],
		"Portrait",		"scene_portrait.bmp",		[(SceneMode)menuSceneModeSet],
		"Night Portrait",		"scene_nightportrait.bmp",		[(SceneMode)menuSceneModeSet],
		"Beach",		"scene_beach.bmp",		[(SceneMode)menuSceneModeSet],
		"Sport",		"scene_sport.bmp",		[(SceneMode)menuSceneModeSet],
		"Dinner",		"scene_dinner.bmp",		[(SceneMode)menuSceneModeSet],
	"Effect",		[(ImageEffect)],
		"Normal",		"dsp_normal.bmp",		[(ImageEffect)menuSnapEffectSet],
		"B&W",		"dsp_bw.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Sepia",		"dsp_sepia.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Negative",		"dsp_negative.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Red",		"dsp_r.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Green",		"dsp_g.bmp",		[(ImageEffect)menuSnapEffectSet],
		"Blue",		"dsp_b.bmp",		[(ImageEffect)menuSnapEffectSet],
	"Exposure",		[(AEMode)menuAEModeInit],
		"-2.0",		"ev_n20.bmp",		[(AEMode)menuAEModeSet],
		"-1.7",		"ev_n17.bmp",		[(AEMode)menuAEModeSet],
		"-1.3",		"ev_n13.bmp",		[(AEMode)menuAEModeSet],
		"-1.0",		"ev_n10.bmp",		[(AEMode)menuAEModeSet],
		"-0.7",		"ev_n07.bmp",		[(AEMode)menuAEModeSet],
		"-0.3",		"ev_n03.bmp",		[(AEMode)menuAEModeSet],
		"+0.0",		"ev_00.bmp",		[(AEMode)menuAEModeSet],
		"+0.3",		"ev_p03.bmp",		[(AEMode)menuAEModeSet],
		"+0.7",		"ev_p07.bmp",		[(AEMode)menuAEModeSet],
		"+1.0",		"ev_p10.bmp",		[(AEMode)menuAEModeSet],
		"+1.3",		"ev_p13.bmp",		[(AEMode)menuAEModeSet],
		"+1.7",		"ev_p17.bmp",		[(AEMode)menuAEModeSet],
		"+2.0",		"ev_p20.bmp",		[(AEMode)menuAEModeSet],
	"White Balance",		[(WBMode)],
		"Auto",		"wb_auto.bmp",		[(WBMode)menuWBModeSet],
		"Daylight",		"wb_day.bmp",		[(WBMode)menuWBModeSet],
		"Cloudy",		"wb_cloudy.bmp",		[(WBMode)menuWBModeSet],
		"Fluorescent",		"wb_flourscent_h.bmp",		[(WBMode)menuWBModeSet],
		"Tungsten",		"wb_tungsten.bmp",		[(WBMode)menuWBModeSet],
	"ISO",		[(Iso)],
		"Auto",		"ISO_Auto.bmp",		[(Iso)menuIsoSet],
		"100",		"ISO_100.bmp",		[(Iso)menuIsoSet],
		"200",		"ISO_200.bmp",		[(Iso)menuIsoSet],
		"400",		"ISO_400.bmp",		[(Iso)menuIsoSet],
		"800",		"ISO_800.bmp",		[(Iso)menuIsoSet],
	"AntiShake",		[(AntiShake)],
		"On",		"on.bmp",		[(AntiShake)menuAntishakeSet],
		"Off",		"off.bmp",		[(AntiShake)menuAntishakeSet],
	"Face Detect",		[menuFDIsActive(FDMode)],
		"On",		"on.bmp",		[(FDMode)menuFDModeSet],
		"Off",		"off.bmp",		[(FDMode)menuFDModeSet],
	"Smile Capture",		[menuFDIsActive(SmileMode)menuLastItemProcess],
		"On",		"on.bmp",		[(SmileMode)menuSmileModeSet],
		"Off",		"off.bmp",		[(SmileMode)menuSmileModeSet],
[MARK]MENU_MARK_VIDEO:
"VideoMenu",		"mode_video.bmp",		[()menuModeVideo],
	"Movie Size",		[(VideoSize)menuMovieSizeInit],
		"1920x1080",		"movie_size_fhd.bmp",		[menuVideoSizeIsActive(VideoSize)menuMovieSizeSet],
		"1280x720",		"movie_size_hd.bmp",		[menuVideoSizeIsActive(VideoSize)menuMovieSizeSet],
		"640x480",		"movie_size_640.bmp",		[(VideoSize)menuMovieSizeSet],
	"Date Stamp",		[(StampMode)],
		"Off",		"off.bmp",		[(StampMode)menuDateStampSet],
		"On",		"on.bmp",		[(StampMode)menuDateStampSet],
	"Exposure",		[(AEMode)menuAEModeInit],
		"-2.0",		"ev_n20.bmp",		[(AEMode)menuAEModeSet],
		"-1.7",		"ev_n17.bmp",		[(AEMode)menuAEModeSet],
		"-1.3",		"ev_n13.bmp",		[(AEMode)menuAEModeSet],
		"-1.0",		"ev_n10.bmp",		[(AEMode)menuAEModeSet],
		"-0.7",		"ev_n07.bmp",		[(AEMode)menuAEModeSet],
		"-0.3",		"ev_n03.bmp",		[(AEMode)menuAEModeSet],
		"+0.0",		"ev_00.bmp",		[(AEMode)menuAEModeSet],
		"+0.3",		"ev_p03.bmp",		[(AEMode)menuAEModeSet],
		"+0.7",		"ev_p07.bmp",		[(AEMode)menuAEModeSet],
		"+1.0",		"ev_p10.bmp",		[(AEMode)menuAEModeSet],
		"+1.3",		"ev_p13.bmp",		[(AEMode)menuAEModeSet],
		"+1.7",		"ev_p17.bmp",		[(AEMode)menuAEModeSet],
		"+2.0",		"ev_p20.bmp",		[(AEMode)menuAEModeSet],
	"White Balance",		[(WBMode)menuLastItemProcess],
		"Auto",		"wb_auto.bmp",		[(WBMode)menuWBModeSet],
		"Daylight",		"wb_day.bmp",		[(WBMode)menuWBModeSet],
		"Cloudy",		"wb_cloudy.bmp",		[(WBMode)menuWBModeSet],
		"Fluorescent",		"wb_flourscent_h.bmp",		[(WBMode)menuWBModeSet],
		"Tungsten",		"wb_tungsten.bmp",		[(WBMode)menuWBModeSet],
[MARK]MENU_MARK_SETUP:
"Setup",		"mode_setup.bmp",		[()menuModeSetup],
	"Date & Time...",		[()menuRTCInit],
		"Year",		[(rtcYear)menuRTCSet],
			"2000",		[(rtcYear)],
			"2001",		[(rtcYear)],
			"2002",		[(rtcYear)],
			"2003",		[(rtcYear)],
			"2004",		[(rtcYear)],
			"2005",		[(rtcYear)],
			"2006",		[(rtcYear)],
			"2007",		[(rtcYear)],
			"2008",		[(rtcYear)],
			"2009",		[(rtcYear)],
			"2010",		[(rtcYear)],
			"2011",		[(rtcYear)],
			"2012",		[(rtcYear)],
			"2013",		[(rtcYear)],
			"2014",		[(rtcYear)],
			"2015",		[(rtcYear)],
			"2016",		[(rtcYear)],
			"2017",		[(rtcYear)],
			"2018",		[(rtcYear)],
			"2019",		[(rtcYear)],
			"2020",		[(rtcYear)],
			"2021",		[(rtcYear)],
			"2022",		[(rtcYear)],
			"2023",		[(rtcYear)],
			"2024",		[(rtcYear)],
			"2025",		[(rtcYear)],
			"2026",		[(rtcYear)],
			"2027",		[(rtcYear)],
			"2028",		[(rtcYear)],
			"2029",		[(rtcYear)],
			"2030",		[(rtcYear)],
		"Month",		[(rtcMonth)menuRTCSet],
			"01",		[(rtcMonth)],
			"02",		[(rtcMonth)],
			"03",		[(rtcMonth)],
			"04",		[(rtcMonth)],
			"05",		[(rtcMonth)],
			"06",		[(rtcMonth)],
			"07",		[(rtcMonth)],
			"08",		[(rtcMonth)],
			"09",		[(rtcMonth)],
			"10",		[(rtcMonth)],
			"11",		[(rtcMonth)],
			"12",		[(rtcMonth)],
		"Day",		[(rtcDay)menuRTCSet],
			"01",		[(rtcDay)],
			"02",		[(rtcDay)],
			"03",		[(rtcDay)],
			"04",		[(rtcDay)],
			"05",		[(rtcDay)],
			"06",		[(rtcDay)],
			"07",		[(rtcDay)],
			"08",		[(rtcDay)],
			"09",		[(rtcDay)],
			"10",		[(rtcDay)],
			"11",		[(rtcDay)],
			"12",		[(rtcDay)],
			"13",		[(rtcDay)],
			"14",		[(rtcDay)],
			"15",		[(rtcDay)],
			"16",		[(rtcDay)],
			"17",		[(rtcDay)],
			"18",		[(rtcDay)],
			"19",		[(rtcDay)],
			"20",		[(rtcDay)],
			"21",		[(rtcDay)],
			"22",		[(rtcDay)],
			"23",		[(rtcDay)],
			"24",		[(rtcDay)],
			"25",		[(rtcDay)],
			"26",		[(rtcDay)],
			"27",		[(rtcDay)],
			"28",		[(rtcDay)],
			"29",		[(rtcDay)],
			"30",		[(rtcDay)],
			"31",		[(rtcDay)],
		"Hour",		[(rtcHour)menuRTCSet],
			"00",		[(rtcHour)],
			"01",		[(rtcHour)],
			"02",		[(rtcHour)],
			"03",		[(rtcHour)],
			"04",		[(rtcHour)],
			"05",		[(rtcHour)],
			"06",		[(rtcHour)],
			"07",		[(rtcHour)],
			"08",		[(rtcHour)],
			"09",		[(rtcHour)],
			"10",		[(rtcHour)],
			"11",		[(rtcHour)],
			"12",		[(rtcHour)],
			"13",		[(rtcHour)],
			"14",		[(rtcHour)],
			"15",		[(rtcHour)],
			"16",		[(rtcHour)],
			"17",		[(rtcHour)],
			"18",		[(rtcHour)],
			"19",		[(rtcHour)],
			"20",		[(rtcHour)],
			"21",		[(rtcHour)],
			"22",		[(rtcHour)],
			"23",		[(rtcHour)],
		"Minute",		[(rtcMinute)menuRTCSet],
			"00",		[(rtcMinute)],
			"01",		[(rtcMinute)],
			"02",		[(rtcMinute)],
			"03",		[(rtcMinute)],
			"04",		[(rtcMinute)],
			"05",		[(rtcMinute)],
			"06",		[(rtcMinute)],
			"07",		[(rtcMinute)],
			"08",		[(rtcMinute)],
			"09",		[(rtcMinute)],
			"10",		[(rtcMinute)],
			"11",		[(rtcMinute)],
			"12",		[(rtcMinute)],
			"13",		[(rtcMinute)],
			"14",		[(rtcMinute)],
			"15",		[(rtcMinute)],
			"16",		[(rtcMinute)],
			"17",		[(rtcMinute)],
			"18",		[(rtcMinute)],
			"19",		[(rtcMinute)],
			"20",		[(rtcMinute)],
			"21",		[(rtcMinute)],
			"22",		[(rtcMinute)],
			"23",		[(rtcMinute)],
			"24",		[(rtcMinute)],
			"25",		[(rtcMinute)],
			"26",		[(rtcMinute)],
			"27",		[(rtcMinute)],
			"28",		[(rtcMinute)],
			"29",		[(rtcMinute)],
			"30",		[(rtcMinute)],
			"31",		[(rtcMinute)],
			"32",		[(rtcMinute)],
			"33",		[(rtcMinute)],
			"34",		[(rtcMinute)],
			"35",		[(rtcMinute)],
			"36",		[(rtcMinute)],
			"37",		[(rtcMinute)],
			"38",		[(rtcMinute)],
			"39",		[(rtcMinute)],
			"40",		[(rtcMinute)],
			"41",		[(rtcMinute)],
			"42",		[(rtcMinute)],
			"43",		[(rtcMinute)],
			"44",		[(rtcMinute)],
			"45",		[(rtcMinute)],
			"46",		[(rtcMinute)],
			"47",		[(rtcMinute)],
			"48",		[(rtcMinute)],
			"49",		[(rtcMinute)],
			"50",		[(rtcMinute)],
			"51",		[(rtcMinute)],
			"52",		[(rtcMinute)],
			"53",		[(rtcMinute)],
			"54",		[(rtcMinute)],
			"55",		[(rtcMinute)],
			"56",		[(rtcMinute)],
			"57",		[(rtcMinute)],
			"58",		[(rtcMinute)],
			"59",		[(rtcMinute)],
		"TimeStyle",		[(DateStyle)menuRTCSet],
			"MM/DD/YYYY",		[(DateStyle)],
			"DD/MM/YYYY",		[(DateStyle)],
			"YYYY/MM/DD",		[(DateStyle)],
	"Language",		[(Language)menuLanguageInit],
		"English",		"language_en.bmp",		[(Language)menuLanguageSet],
		"\x08",		"language_cs.bmp",		[(Language)menuLanguageSet],
		"\x09",		"language_ct.bmp",		[(Language)menuLanguageSet],
		"\x0a",		"lan_French.bmp",		[(Language)menuLanguageSet],
		"\x0b",		"lan_Spanlish.bmp",		[(Language)menuLanguageSet],
		"\x0c",		"lan_German.bmp",		[(Language)menuLanguageSet],
		"\x0d",		"lan_Italian.bmp",		[(Language)menuLanguageSet],
		"\x0e",		"lan_Portuguese.bmp",		[(Language)menuLanguageSet],
		"\x0f",		"lan_Dutch.bmp",		[(Language)menuLanguageSet],
		"\x10",		"lan_Japanese.bmp",		[(Language)menuLanguageSet],
		"\x11",		"lan_Russian.bmp",		[(Language)menuLanguageSet],
		"\x12",		"lan_Arabic.bmp",		[(Language)menuLanguageSet],
	"Sounds...",		[(SpeakSound)],
		"Off",		"off.bmp",		[(SpeakSound)menuSpeakSoundSet],
		"On",		"on.bmp",		[(SpeakSound)menuSpeakSoundSet],
	"Power frequency",		[(LightFreq)],
		"50Hz",		"frequency_50.bmp",		[(LightFreq)],
		"60Hz",		"frequency_60.bmp",		[(LightFreq)],
	"Power Save",		[(SleepTime)],
		"1min.",		"power_save_1min.bmp",		[(SleepTime)],
		"3min.",		"power_save_3min.bmp",		[(SleepTime)],
		"5min.",		"power_save_5min.bmp",		[(SleepTime)],
		"OFF",		"off.bmp",		[(SleepTime)],
	"Format...",
		"Yes",		[()menuFormatSet],
		"No",		[()menuFormatSet],
	"Reset All...",
		"Yes",		[()menuResetSet],
		"No",
	"Version",		[()menuLastItemProcess],
		"M03",		[()menuVersionProcess],
		"20240226",
		"_00:00:00",
"Card Error",
	"Card Error",
		"Format...",
[MARK]MENU_MARK_FORMAT_YES:
			"Yes",		[()menuFormatSet],
[MARK]MENU_MARK_FORMAT_NO:
			"No",		[()menuFormatSet],
		"Delete This File?",
[MARK]MENU_MARK_DELONE_YES:
			"Yes",		[()menuDeleteOne],
[MARK]MENU_MARK_DELONE_NO:
			"No",		[()menuDeleteOne],
		"Detecting Blinking...",
[MARK]MENU_MARK_BLINK_SAVE:
			"Save",		[()menuBlinkSave],
[MARK]MENU_MARK_BLINK_CANCEL:
			"Cancel",		[()menuBlinkSave],
		"Crop this photo?",
[MARK]MENU_MARK_JPG_CROP_YES:
			"Yes",		[()menuJpgCrop],
[MARK]MENU_MARK_JPG_CROP_NO:
			"No",		[()menuJpgCrop],
"RedEyeSave",
[MARK]MENU_MARK_REDEYE_WRITE:
	"OverWrite",		[()menuRedEyeSave],
[MARK]MENU_MARK_REDEYE_SAVE:
	"Save as",		[()menuRedEyeSave],
[MARK]MENU_MARK_REDEYE_CANCEL:
	"Cancel",		[()menuRedEyeSave],
[MARK]MENU_MARK_DPS:
"Dps",		"PRINT.bmp",		[()menuModeDPS],
	"Image",		[(DPSImageMode)menuFirstItemProcess],
		"Single",		[(DPSImageMode)menuDpsImageChoose],
		"All",		[(DPSImageMode)menuDpsImageChoose],
		"Choose",		[(DPSImageMode)menuDpsImageChoose],
	"Copy",		[()menuDpsCopyInit],
		"Copies",		[(DPSCopies)menuDpsCpoySet],
			"01",		[(DPSCopies)],
			"02",		[(DPSCopies)],
			"03",		[(DPSCopies)],
			"04",		[(DPSCopies)],
			"05",		[(DPSCopies)],
			"06",		[(DPSCopies)],
			"07",		[(DPSCopies)],
			"08",		[(DPSCopies)],
			"09",		[(DPSCopies)],
			"10",		[(DPSCopies)],
			"11",		[(DPSCopies)],
			"12",		[(DPSCopies)],
			"13",		[(DPSCopies)],
			"14",		[(DPSCopies)],
			"15",		[(DPSCopies)],
			"16",		[(DPSCopies)],
			"17",		[(DPSCopies)],
			"18",		[(DPSCopies)],
			"19",		[(DPSCopies)],
			"20",		[(DPSCopies)],
			"21",		[(DPSCopies)],
			"22",		[(DPSCopies)],
			"23",		[(DPSCopies)],
			"24",		[(DPSCopies)],
			"25",		[(DPSCopies)],
			"26",		[(DPSCopies)],
			"27",		[(DPSCopies)],
			"28",		[(DPSCopies)],
			"29",		[(DPSCopies)],
			"30",		[(DPSCopies)],
			"31",		[(DPSCopies)],
			"32",		[(DPSCopies)],
			"33",		[(DPSCopies)],
			"34",		[(DPSCopies)],
			"35",		[(DPSCopies)],
			"36",		[(DPSCopies)],
			"37",		[(DPSCopies)],
			"38",		[(DPSCopies)],
			"39",		[(DPSCopies)],
			"40",		[(DPSCopies)],
			"41",		[(DPSCopies)],
			"42",		[(DPSCopies)],
			"43",		[(DPSCopies)],
			"44",		[(DPSCopies)],
			"45",		[(DPSCopies)],
			"46",		[(DPSCopies)],
			"47",		[(DPSCopies)],
			"48",		[(DPSCopies)],
			"49",		[(DPSCopies)],
			"50",		[(DPSCopies)],
			"51",		[(DPSCopies)],
			"52",		[(DPSCopies)],
			"53",		[(DPSCopies)],
			"54",		[(DPSCopies)],
			"55",		[(DPSCopies)],
			"56",		[(DPSCopies)],
			"57",		[(DPSCopies)],
			"58",		[(DPSCopies)],
			"59",		[(DPSCopies)],
			"60",		[(DPSCopies)],
			"61",		[(DPSCopies)],
			"62",		[(DPSCopies)],
			"63",		[(DPSCopies)],
			"64",		[(DPSCopies)],
			"65",		[(DPSCopies)],
			"66",		[(DPSCopies)],
			"67",		[(DPSCopies)],
			"68",		[(DPSCopies)],
			"69",		[(DPSCopies)],
			"70",		[(DPSCopies)],
			"71",		[(DPSCopies)],
			"72",		[(DPSCopies)],
			"73",		[(DPSCopies)],
			"74",		[(DPSCopies)],
			"75",		[(DPSCopies)],
			"76",		[(DPSCopies)],
			"77",		[(DPSCopies)],
			"78",		[(DPSCopies)],
			"79",		[(DPSCopies)],
			"80",		[(DPSCopies)],
			"81",		[(DPSCopies)],
			"82",		[(DPSCopies)],
			"83",		[(DPSCopies)],
			"84",		[(DPSCopies)],
			"85",		[(DPSCopies)],
			"86",		[(DPSCopies)],
			"87",		[(DPSCopies)],
			"88",		[(DPSCopies)],
			"89",		[(DPSCopies)],
			"90",		[(DPSCopies)],
			"91",		[(DPSCopies)],
			"92",		[(DPSCopies)],
			"93",		[(DPSCopies)],
			"94",		[(DPSCopies)],
			"95",		[(DPSCopies)],
			"96",		[(DPSCopies)],
			"97",		[(DPSCopies)],
			"98",		[(DPSCopies)],
			"99",		[(DPSCopies)],
	"Quality",		[(DPSQuality)],
		"Auto",		[menuDpsQualityIsActive(DPSQuality)],
		"Fine",		[menuDpsQualityIsActive(DPSQuality)],
		"Normal",		[menuDpsQualityIsActive(DPSQuality)],
		"Draft",		[menuDpsQualityIsActive(DPSQuality)],
	"Layout",		[(DPSLayout)],
		"Auto",		[menuDpsLayoutIsActive(DPSLayout)],
		"1",		[menuDpsLayoutIsActive(DPSLayout)],
		"2",		[menuDpsLayoutIsActive(DPSLayout)],
		"4",		[menuDpsLayoutIsActive(DPSLayout)],
		"6",		[menuDpsLayoutIsActive(DPSLayout)],
		"8",		[menuDpsLayoutIsActive(DPSLayout)],
		"Full",		[menuDpsLayoutIsActive(DPSLayout)],
		"Index",		[menuDpsLayoutIsActive(DPSLayout)],
	"Page Size",		[(DPSPageSize)],
		"Auto",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"L",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"2L",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"100x150(mm)",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"Postcard",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"4\ x 6\",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"8\ x 10\",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"Letter",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"A4",		[menuDpsPaperSizeIsActive(DPSPageSize)],
		"A3",		[menuDpsPaperSizeIsActive(DPSPageSize)],
	"Paper Type",		[(DPSPageType)],
		"Auto",		[menuDpsTypeIsActive(DPSPageType)],
		"Plain",		[menuDpsTypeIsActive(DPSPageType)],
		"Photo",		[menuDpsTypeIsActive(DPSPageType)],
		"F.Photo",		[menuDpsTypeIsActive(DPSPageType)],
	"Date",		[(DPSDate)],
		"Auto",		[menuDpsDateIsActive(DPSDate)],
		"Off",		[menuDpsDateIsActive(DPSDate)],
		"On",		[menuDpsDateIsActive(DPSDate)],
	"File No.",		[(DPSFileName)],
		"Auto",		[menuDpsNameIsActive(DPSFileName)],
		"Off",		[menuDpsNameIsActive(DPSFileName)],
		"On",		[menuDpsNameIsActive(DPSFileName)],
	"DpsReset",		[()menuLastItemProcess],
		"Yes",		[()menuDPSResetSet],
		"No",
[MARK]MENU_MARK_CALIBRATION:
"Calibration",		"mode_still.bmp",		[()menuModeCalibration],
	"USB power mode",		[menuUSBPowerIsActive()menuCalUsbPowerSet],
	"CDSP configure",
		"OB",		[(cal_ob)],
			"Off",		[(cal_ob)menuCalCDSP_OBSet],
			"On",		[(cal_ob)menuCalCDSP_OBSet],
		"Lens shading",		[(cal_lc)],
			"Off",		[(cal_lc)menuCalCDSP_LensShadingSet],
			"On",		[(cal_lc)menuCalCDSP_LensShadingSet],
		"Gamma",		[(cal_gma)],
			"Off",		[(cal_gma)menuCalCDSP_GammaSet],
			"On",		[(cal_gma)menuCalCDSP_GammaSet],
		"AE",		[(cal_ae)],
			"Manual",		[(cal_ae)menuCalCDSP_AESet],
			"Auto",		[(cal_ae)menuCalCDSP_AESet],
			"Lsc",		[(cal_ae)menuCalCDSP_AESet],
			"Color Checker",		[(cal_ae)menuCalCDSP_AESet],
		"AE Gid +/-",
			"000",		[()menuCalCDSP_AEGidSet],
			"001",		[()menuCalCDSP_AEGidSet],
			"002",		[()menuCalCDSP_AEGidSet],
			"003",		[()menuCalCDSP_AEGidSet],
			"004",		[()menuCalCDSP_AEGidSet],
			"005",		[()menuCalCDSP_AEGidSet],
			"006",		[()menuCalCDSP_AEGidSet],
			"007",		[()menuCalCDSP_AEGidSet],
			"008",		[()menuCalCDSP_AEGidSet],
			"009",		[()menuCalCDSP_AEGidSet],
			"010",		[()menuCalCDSP_AEGidSet],
			"011",		[()menuCalCDSP_AEGidSet],
			"012",		[()menuCalCDSP_AEGidSet],
			"013",		[()menuCalCDSP_AEGidSet],
			"014",		[()menuCalCDSP_AEGidSet],
			"015",		[()menuCalCDSP_AEGidSet],
			"016",		[()menuCalCDSP_AEGidSet],
			"017",		[()menuCalCDSP_AEGidSet],
			"018",		[()menuCalCDSP_AEGidSet],
			"019",		[()menuCalCDSP_AEGidSet],
			"020",		[()menuCalCDSP_AEGidSet],
			"021",		[()menuCalCDSP_AEGidSet],
			"022",		[()menuCalCDSP_AEGidSet],
			"023",		[()menuCalCDSP_AEGidSet],
			"024",		[()menuCalCDSP_AEGidSet],
			"025",		[()menuCalCDSP_AEGidSet],
			"026",		[()menuCalCDSP_AEGidSet],
			"027",		[()menuCalCDSP_AEGidSet],
			"028",		[()menuCalCDSP_AEGidSet],
			"029",		[()menuCalCDSP_AEGidSet],
			"030",		[()menuCalCDSP_AEGidSet],
			"031",		[()menuCalCDSP_AEGidSet],
			"032",		[()menuCalCDSP_AEGidSet],
			"033",		[()menuCalCDSP_AEGidSet],
			"034",		[()menuCalCDSP_AEGidSet],
			"035",		[()menuCalCDSP_AEGidSet],
			"036",		[()menuCalCDSP_AEGidSet],
			"037",		[()menuCalCDSP_AEGidSet],
			"038",		[()menuCalCDSP_AEGidSet],
			"039",		[()menuCalCDSP_AEGidSet],
			"040",		[()menuCalCDSP_AEGidSet],
			"041",		[()menuCalCDSP_AEGidSet],
			"042",		[()menuCalCDSP_AEGidSet],
			"043",		[()menuCalCDSP_AEGidSet],
			"044",		[()menuCalCDSP_AEGidSet],
			"045",		[()menuCalCDSP_AEGidSet],
			"046",		[()menuCalCDSP_AEGidSet],
			"047",		[()menuCalCDSP_AEGidSet],
			"048",		[()menuCalCDSP_AEGidSet],
			"049",		[()menuCalCDSP_AEGidSet],
			"050",		[()menuCalCDSP_AEGidSet],
			"051",		[()menuCalCDSP_AEGidSet],
			"052",		[()menuCalCDSP_AEGidSet],
			"053",		[()menuCalCDSP_AEGidSet],
			"054",		[()menuCalCDSP_AEGidSet],
			"055",		[()menuCalCDSP_AEGidSet],
			"056",		[()menuCalCDSP_AEGidSet],
			"057",		[()menuCalCDSP_AEGidSet],
			"058",		[()menuCalCDSP_AEGidSet],
			"059",		[()menuCalCDSP_AEGidSet],
			"060",		[()menuCalCDSP_AEGidSet],
			"061",		[()menuCalCDSP_AEGidSet],
			"062",		[()menuCalCDSP_AEGidSet],
			"063",		[()menuCalCDSP_AEGidSet],
			"064",		[()menuCalCDSP_AEGidSet],
			"065",		[()menuCalCDSP_AEGidSet],
			"066",		[()menuCalCDSP_AEGidSet],
			"067",		[()menuCalCDSP_AEGidSet],
			"068",		[()menuCalCDSP_AEGidSet],
			"069",		[()menuCalCDSP_AEGidSet],
			"070",		[()menuCalCDSP_AEGidSet],
			"071",		[()menuCalCDSP_AEGidSet],
			"072",		[()menuCalCDSP_AEGidSet],
			"073",		[()menuCalCDSP_AEGidSet],
			"074",		[()menuCalCDSP_AEGidSet],
			"075",		[()menuCalCDSP_AEGidSet],
			"076",		[()menuCalCDSP_AEGidSet],
			"077",		[()menuCalCDSP_AEGidSet],
			"078",		[()menuCalCDSP_AEGidSet],
			"079",		[()menuCalCDSP_AEGidSet],
			"080",		[()menuCalCDSP_AEGidSet],
			"081",		[()menuCalCDSP_AEGidSet],
			"082",		[()menuCalCDSP_AEGidSet],
			"083",		[()menuCalCDSP_AEGidSet],
			"084",		[()menuCalCDSP_AEGidSet],
			"085",		[()menuCalCDSP_AEGidSet],
			"086",		[()menuCalCDSP_AEGidSet],
			"087",		[()menuCalCDSP_AEGidSet],
			"088",		[()menuCalCDSP_AEGidSet],
			"089",		[()menuCalCDSP_AEGidSet],
			"090",		[()menuCalCDSP_AEGidSet],
			"091",		[()menuCalCDSP_AEGidSet],
			"092",		[()menuCalCDSP_AEGidSet],
			"093",		[()menuCalCDSP_AEGidSet],
			"094",		[()menuCalCDSP_AEGidSet],
			"095",		[()menuCalCDSP_AEGidSet],
			"096",		[()menuCalCDSP_AEGidSet],
			"097",		[()menuCalCDSP_AEGidSet],
			"098",		[()menuCalCDSP_AEGidSet],
			"099",		[()menuCalCDSP_AEGidSet],
			"100",		[()menuCalCDSP_AEGidSet],
		"AWB",		[(cal_awb)],
			"Off",		[(cal_awb)menuCalCDSP_AWBSet],
			"On",		[(cal_awb)menuCalCDSP_AWBSet],
	"Snap",
		"Snap Raw",		[()menuCalSnapTest],
		"Snap Pure",		[()menuCalSnapTest],
		"Snap IQ Raw",		[()menuCalSnapTest],
	"Pv",
		"Pv Raw",		[()menuCalPvTest],
		"PV Pure Raw",		[()menuCalPvTest],
		"Pv YUV",		[()menuCalPvTest],
	"AE Test",
		"Test Part 1",		[()menuCalAETest],
		"Test Part 2",		[()menuCalAETest],
		"Test Part 3",		[()menuCalAETest],
		"Save",		[()menuCalAETest],
	"OB Calibration",		[()menuCalOB],
	"Auto OB",		[()menuCalAutoOB],
	"PV OB Mode",		[()menuCalPvOB],
	"AWB Test",		[()menuCalAWBTest],
	"BadPixel",
		"Preview BP_HD",		[()menuCalBpPro],
		"Preview BP",		[()menuCalBpPro],
		"Capture BP",		[()menuCalBpPro],
		"Process All",		[()menuCalBpPro],
	"AF Turing",
		"2A Start",		[()menuCalAFTurn],
		"2A Stop",		[()menuCalAFTurn],
		"Start",		[()menuCalAFTurn],
	"FW UPGRADE",		[()menuCalFwUpgrade],
	"Standalone Lsc",		[()menuCalLsc],
	"AE_CALIBRATION",		[()menuCalAECal],
	"Watch Dog",		[(cal_wdr)],
		"Off",		[(cal_wdr)menuCalWdtSet],
		"On",		[(cal_wdr)menuCalWdtSet],
	"ColorPalette",
		"Show",		[()menuCalShowColorPalette],
	"StorageSpeedTest",		[()menuStorageSpeedTest],
	"AWB Cal Stand-along",
		"Isctt",		[()menuCalAwbCtt],
		"Lv10",		[()menuCalAwbCtt],
[MARK]MENU_MARK_USB:
"USB",		[(USBMode)],
	"Mass Storage",		"usb_computer.bmp",		[(USBMode)menuModeUsbSet],
	"PC Camera",		"usb_camera.bmp",		[(USBMode)menuModeUsbSet],

[STRING]:
	"Enter",
	"Back",
	"Delete This File?",
	"Delete All File?",
	"Formatting...",
	"Has no size to risize!",
	"File Locked!",
	"Protect File?",
	"Unprotect File?",
	"Protect All?",
	"Unprotect All?",
	"No File",
	"No Card!",
	"Remove Card!",
	"Card Error",
	"Waiting...",
	"Card Locked!",
	"PAUSE",
	"REC",
	"File Error!",
	"Please plug out card",
	"Memory Full",
	"Waiting for printer",
	"No Jpeg",
	"Format Fail!",
	"Low Battery",
	"Not Support!",
	"Cancel",
	"Select up to 24",
	"Please select a picture",
	"Print Error",
	"Not Find Printer",
	"Crop this photo?",
	"up_no",
	"up_yes",
	"down_no",
	"down_yes",
	"ok_no",
	"ok_yes",
	"pwr_no",
	"pwr_yes",
	"usb_no",
	"usb_yes",
	"pb_no",
	"pb_yes",
	"set_no",
	"set_yes",
	"Adjust Macro?",
	"Software update...",
	"Update completed!",
	"Update failed!",
	"DC403S-5647-9851-221220",

#endif /* _MENU_RES_H_ */
